### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI532_Youtube-Trending#6]
-Good choice of data set, your idea is interesting and the scenario makes sense. 
-Description of the app is good overall. Section 2 lacks a bit of detail describing the variables you will be using.
-The sketch of the app has a nice design, however it's not self-explanatory. Adding arrows labeling each thing would be more helpful to understand all of the plots you will be adding.

**Comment by jackattackyang** [comment]
Noted thank you!
